AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    Function

Globals:
    Function:
        Timeout: 300

Resources:
    HelloWorldFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: build/
            Handler: app.lambdaHandler
            Runtime: nodejs8.10